onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@corsair-dev/googlecalendar@0.1.4'
